import { LearningContent, FinanceSeriesEpisode, GlossaryTerm } from "../types";

export const LEARNING_CONTENT: LearningContent[] = [
  {
    id: "art-001",
    type: "article",
    category: "Budgeting",
    isFeatured: true,
    title: "How to Stop Overspending as a Student",
    duration: "3 min read",
    content: "Budgeting for OAU students can be challenging, especially with the lure of night snacks at Sub or the temptation of quick trips into town. The first step to financial freedom is tracking. Every bottle of Coke, every share in a bike ride, and every handout bought must be recorded.\n\nMost students fail because they confuse 'wants' with 'needs'. While that new pair of sneakers might feel like a need for that upcoming department social, it is likely a want. Prioritizing your tuition, accommodation, and basic feeding ensures you never find yourself stranded mid-semester.\n\nBy following a strict 50/30/20 rule—50% for needs, 30% for wants, and 20% for savings—you can build a safety net. Even a small saving of 500 Naira a week can grow into something significant by the end of the session.",
    keyTakeaways: [
      "Separate needs from wants",
      "Use the 50/30/20 rule",
      "Track every expense daily",
      "Review your spending weekly",
    ],
    relatedContentIds: ["art-002", "vid-001"],
  },
  {
    id: "art-002",
    type: "article",
    category: "Saving",
    isFeatured: false,
    title: "Why You Always Run Out of Money",
    duration: "3 min read",
    content: "It starts with a small treat here and a 'loan' to a friend there. Before you know it, your account balance is single digits and you're calling home for emergency funds. The 'Sapa' cycle is often caused by a lack of visibility into your future expenses.\n\nWhen you don't plan for the unexpected handout cost or the hike in transport fare, you are forced to dip into your food money. This creates a domino effect that ruins your finances for the rest of the month.",
    keyTakeaways: ["Build an emergency fund", "Plan for handout costs", "Learn to say no to lending when you can't afford it"],
  },
  {
    id: "vid-001",
    type: "video",
    category: "Budgeting",
    isFeatured: true,
    title: "How to Create Your First Budget",
    duration: "5 min",
    content: "In this short guide, we break down the simple steps to creating a budget that actually works for a Nigerian student. We cover how to estimate your monthly allowance and how to categorize your spending effectively.",
  },
  {
    id: "pod-001",
    type: "podcast",
    category: "Finance",
    isFeatured: false,
    title: "The Nigerian Economy Explained",
    duration: "15 min",
    episodeNumber: 1,
    content: "BOF OAU breaks down why students run out of money and how to fix it for good. Join us as we discuss the psychology of spending on campus and how to build wealth from your allowance.",
  },
  {
    id: "art-003",
    type: "article",
    category: "Investing",
    isFeatured: false,
    title: "Intro to Stock Market for Students",
    duration: "4 min read",
    content: "Investing isn't just for billionaires. With as little as 1,000 Naira, you can start owning pieces of the biggest companies in Nigeria and abroad. This article covers the basics of stocks, dividends, and long-term growth.",
  },
  {
    id: "vid-002",
    type: "video",
    category: "Saving",
    isFeatured: false,
    title: "The Power of Compound Interest",
    duration: "6 min",
    content: "Watch how saving just a small amount consistently can lead to huge returns over time. We use real-world examples that students can relate to.",
  },
  {
    id: "art-004",
    type: "article",
    category: "Debt",
    isFeatured: false,
    title: "Managing Student Loans and Debts",
    duration: "5 min read",
    content: "Debt can be a tool or a trap. Learn how to identify good debt vs bad debt and strategies to pay off your 'borrow-me-credit' and other small loans quickly.",
  },
  {
    id: "pod-002",
    type: "podcast",
    category: "Career",
    isFeatured: false,
    title: "How to Invest in Stocks Locally",
    duration: "20 min",
    episodeNumber: 2,
    content: "We interview three students who have built successful businesses while maintaining their CGPAs. Learn how to balance work and study.",
  },
  {
    id: "pod-003",
    type: "podcast",
    category: "Crypto",
    isFeatured: false,
    title: "Crypto in Nigeria — Risk & Reward?",
    duration: "18 min",
    episodeNumber: 3,
    content: "An deep dive into the world of digital currencies in Nigeria. Is it still worth it in 2025?",
  },
];

export const FINANCE_101_SERIES: FinanceSeriesEpisode[] = [
  {
    id: "f101-01",
    title: "Budgeting Basics",
    duration: "5 min read",
    episodeNumber: 1,
    content: "The foundation of all wealth is understanding where your money goes. Learn how to categorize your expenses and set limits.",
  },
  {
    id: "f101-02",
    title: "Saving as a Student",
    duration: "4 min read",
    episodeNumber: 2,
    content: "Saving on campus isn't about how much you have, but how much you keep. We explore practical ways to cut back on unnecessary costs.",
  },
  {
    id: "f101-03",
    title: "Intro to Investing",
    duration: "6 min read",
    episodeNumber: 3,
    content: "Making your money work for you. We explain the difference between assets and liabilities in simple terms.",
  },
  {
    id: "f101-04",
    title: "Understanding Loans",
    duration: "5 min read",
    episodeNumber: 4,
    content: "The pros and cons of borrowing. Learn about interest rates and how they can affect your future financial health.",
  },
  {
    id: "f101-05",
    title: "Credit Scores Explained",
    duration: "4 min read",
    episodeNumber: 5,
    content: "Why your financial reputation matters. How to build a good credit score starting with your small bills.",
  },
  {
    id: "f101-06",
    title: "How Inflation Affects You",
    duration: "3 min read",
    episodeNumber: 6,
    content: "Why 500 Naira bought more yesterday than today. Learn how to protect your savings from the rising cost of living.",
  },
  {
    id: "f101-07",
    title: "Building an Emergency Fund",
    duration: "5 min read",
    episodeNumber: 7,
    content: "Preparing for the rainy day on campus. Why you need a safety net and how to start building one today.",
  },
  {
    id: "f101-08",
    title: "Financial Goals Setting",
    duration: "4 min read",
    episodeNumber: 8,
    content: "Turning dreams into reality. How to set SMART financial goals and track your progress effectively.",
  },
];

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    id: "gt-001",
    term: "Asset",
    partOfSpeech: "noun",
    definition: "Anything of value owned by a person or organization.",
    example: "A savings account or a laptop used for freelance work are examples of student assets.",
    relatedTerms: ["Equity", "Investment", "Net Worth"],
  },
  {
    id: "gt-002",
    term: "Allowance",
    partOfSpeech: "noun",
    definition: "A sum of money allotted or granted to a person on a regular basis, as for personal expenses.",
    example: "The 20,000 Naira monthly allowance from my parents is my primary source of income.",
    relatedTerms: ["Income", "Budget", "Cash Flow"],
  },
  {
    id: "gt-003",
    term: "Appreciation",
    partOfSpeech: "noun",
    definition: "An increase in the value of an asset over time.",
    example: "The value of the land my father bought ten years ago has seen significant appreciation.",
    relatedTerms: ["Depreciation", "Investment", "Inflation"],
  },
  {
    id: "gt-004",
    term: "Balance",
    partOfSpeech: "noun",
    definition: "The amount of money in a financial account.",
    example: "I need to check my account balance before I buy this textbook.",
    relatedTerms: ["Transaction", "Savings", "Cash Flow"],
  },
  {
    id: "gt-005",
    term: "Budget",
    partOfSpeech: "noun",
    definition: "A plan that shows how much money you can spend in a period",
    example: "I created a monthly budget to make sure I have enough for both food and handouts.",
    relatedTerms: ["Expense", "Income", "Savings"],
  },
  {
    id: "gt-meta",
    term: "Financial Glossary",
    partOfSpeech: "noun",
    definition: "Learn key money terms simply explained",
    example: "Use this glossary to understand complex financial concepts.",
    relatedTerms: ["Learning", "Finance", "Education"],
  },
  {
    id: "gt-017",
    term: "Interest",
    partOfSpeech: "noun",
    definition: "Extra money you earn or pay when saving or borrowing money",
    example: "The high interest rate on my loan made it difficult to pay back quickly.",
    relatedTerms: ["Loan", "Debt", "Compound Interest"],
  },
  {
    id: "gt-006",
    term: "Bond",
    partOfSpeech: "noun",
    definition: "A fixed income instrument that represents a loan made by an investor to a borrower.",
    example: "Investing in government bonds is generally considered safer than stocks.",
    relatedTerms: ["Investment", "Stock", "Interest"],
  },
  {
    id: "gt-007",
    term: "Credit Score",
    partOfSpeech: "noun",
    definition: "A numerical expression based on a level analysis of a person's credit files, representing their creditworthiness.",
    example: "Paying your bills on time helps you build a strong credit score.",
    relatedTerms: ["Loan", "Debt", "Interest"],
  },
  {
    id: "gt-008",
    term: "Cash Flow",
    partOfSpeech: "noun",
    definition: "The total amount of money being transferred into and out of a business or household.",
    example: "Tracking your daily expenses helps you understand your monthly cash flow.",
    relatedTerms: ["Income", "Expense", "Balance"],
  },
  {
    id: "gt-009",
    term: "Compound Interest",
    partOfSpeech: "noun",
    definition: "Interest calculated on the principal amount and also on the accumulated interest of previous periods.",
    example: "Compound interest is the secret to building long-term wealth.",
    relatedTerms: ["Interest", "Savings", "Investment"],
  },
  {
    id: "gt-010",
    term: "Debt",
    partOfSpeech: "noun",
    definition: "Something, typically money, that is owed or due.",
    example: "I need to pay off my debt to the canteen before the end of the week.",
    relatedTerms: ["Loan", "Credit Score", "Interest"],
  },
  {
    id: "gt-011",
    term: "Dividend",
    partOfSpeech: "noun",
    definition: "A sum of money paid regularly by a company to its shareholders out of its profits.",
    example: "The company announced a 10 Naira dividend for every share owned.",
    relatedTerms: ["Stock", "Investment", "Income"],
  },
  {
    id: "gt-012",
    term: "Depreciation",
    partOfSpeech: "noun",
    definition: "A reduction in the value of an asset over time, particularly due to wear and tear.",
    example: "A new car begins to experience depreciation the moment it is driven away.",
    relatedTerms: ["Appreciation", "Asset", "Tax"],
  },
  {
    id: "gt-013",
    term: "Expense",
    partOfSpeech: "noun",
    definition: "The cost required for something; the money spent on something.",
    example: "Transport to class is my biggest daily expense.",
    relatedTerms: ["Budget", "Income", "Transaction"],
  },
  {
    id: "gt-014",
    term: "Emergency Fund",
    partOfSpeech: "noun",
    definition: "Money set aside to cover large, unexpected expenses.",
    example: "My emergency fund helped me pay for my broken laptop screen without stress.",
    relatedTerms: ["Savings", "Budget", "Cash Flow"],
  },
  {
    id: "gt-015",
    term: "Equity",
    partOfSpeech: "noun",
    definition: "The value of the shares issued by a company.",
    example: "Owning equity in a startup can be very profitable if the company succeeds.",
    relatedTerms: ["Stock", "Asset", "Dividend"],
  },
  {
    id: "gt-016",
    term: "Income",
    partOfSpeech: "noun",
    definition: "Money received, especially on a regular basis, for work or through investments.",
    example: "My income from tutoring helps me supplement my monthly allowance.",
    relatedTerms: ["Allowance", "Dividend", "Budget"],
  },
  {
    id: "gt-018",
    term: "Investment",
    partOfSpeech: "noun",
    definition: "The action or process of investing money for profit or material result.",
    example: "Buying mutual funds is a great first investment for students.",
    relatedTerms: ["Stock", "Bond", "Appreciation"],
  },
  {
    id: "gt-019",
    term: "Inflation",
    partOfSpeech: "noun",
    definition: "A general increase in prices and fall in the purchasing value of money.",
    example: "Inflation means that my allowance doesn't buy as much food as it did last year.",
    relatedTerms: ["Appreciation", "Depreciation", "Cash Flow"],
  },
  {
    id: "gt-020",
    term: "Loan",
    partOfSpeech: "noun",
    definition: "A thing that is borrowed, especially a sum of money that is expected to be paid back with interest.",
    example: "I took a small loan from my friend to buy a mandatory textbook.",
    relatedTerms: ["Debt", "Interest", "Credit Score"],
  },
  {
    id: "gt-021",
    term: "Net Worth",
    partOfSpeech: "noun",
    definition: "The total wealth of an individual, calculated as total assets minus total liabilities.",
    example: "Tracking your assets and debts helps you calculate your personal net worth.",
    relatedTerms: ["Asset", "Debt", "Equity"],
  },
  {
    id: "gt-022",
    term: "Savings",
    partOfSpeech: "noun",
    definition: "The money that a person keeps in an account or elsewhere for future use.",
    example: "Setting up an automatic transfer is an easy way to grow your savings.",
    relatedTerms: ["Emergency Fund", "Balance", "Compound Interest"],
  },
  {
    id: "gt-023",
    term: "Stock",
    partOfSpeech: "noun",
    definition: "The capital raised by a business or corporation through the issue and subscription of shares.",
    example: "I bought some tech stocks because I believe in the future of AI.",
    relatedTerms: ["Equity", "Dividend", "Investment"],
  },
  {
    id: "gt-024",
    term: "Tax",
    partOfSpeech: "noun",
    definition: "A compulsory contribution to state revenue, levied by the government on workers' income and business profits.",
    example: "VAT is a common type of tax that we pay on most goods we buy.",
    relatedTerms: ["Income", "Expense", "Depreciation"],
  },
  {
    id: "gt-025",
    term: "Transaction",
    partOfSpeech: "noun",
    definition: "An instance of buying or selling something; a business deal.",
    example: "I reviewed my bank statement to check all my recent transactions.",
    relatedTerms: ["Balance", "Expense", "Income"],
  },
  {
    id: "gt-026",
    term: "Equity",
    partOfSpeech: "noun",
    definition: "The value of the shares issued by a company.",
    example: "Founders usually hold a large amount of equity in their startups.",
    relatedTerms: ["Stock", "Asset", "Net Worth"],
  },
  {
    id: "gt-027",
    term: "Fixed Income",
    partOfSpeech: "noun",
    definition: "An investment that provides a return in the form of fixed periodic payments.",
    example: "Bonds are a common type of fixed income investment.",
    relatedTerms: ["Bond", "Interest", "Dividend"],
  },
  {
    id: "gt-028",
    term: "Gross Income",
    partOfSpeech: "noun",
    definition: "Total pay before taxes and other deductions.",
    example: "My gross income looks great, but taxes take a chunk out of it.",
    relatedTerms: ["Tax", "Salary", "Income"],
  },
  {
    id: "gt-029",
    term: "Hedge",
    partOfSpeech: "verb",
    definition: "An investment to reduce the risk of adverse price movements in an asset.",
    example: "Investors often buy gold to hedge against inflation.",
    relatedTerms: ["Risk", "Inflation", "Investment"],
  },
  {
    id: "gt-030",
    term: "Junk Bond",
    partOfSpeech: "noun",
    definition: "A high-yield, high-risk security, typically issued by a company seeking to raise capital quickly.",
    example: "Junk bonds offer higher returns but carry a significant risk of default.",
    relatedTerms: ["Bond", "Risk", "Interest"],
  },
  {
    id: "gt-031",
    term: "KYC",
    partOfSpeech: "noun",
    definition: "Know Your Customer; a process used by financial institutions to verify the identity of their clients.",
    example: "I had to complete my KYC verification before I could open a bank account.",
    relatedTerms: ["Bank", "Transaction", "Regulation"],
  },
  {
    id: "gt-032",
    term: "Money Market",
    partOfSpeech: "noun",
    definition: "The trade in short-term loans between banks and other financial institutions.",
    example: "Money market funds are considered safe, low-risk investments.",
    relatedTerms: ["Interest", "Investment", "Liquidity"],
  },
  {
    id: "gt-033",
    term: "Opportunity Cost",
    partOfSpeech: "noun",
    definition: "The loss of potential gain from other alternatives when one alternative is chosen.",
    example: "The opportunity cost of buying a new phone is the money I could have saved.",
    relatedTerms: ["Budget", "Investment", "Savings"],
  },
  {
    id: "gt-034",
    term: "Ponzi Scheme",
    partOfSpeech: "noun",
    definition: "A form of fraud that lures investors and pays profits to earlier investors with funds from more recent investors.",
    example: "Many students lost money in the latest Ponzi scheme promising 50% returns in a week.",
    relatedTerms: ["Risk", "Fraud", "Investment"],
  },
  {
    id: "gt-035",
    term: "Quantitative Easing",
    partOfSpeech: "noun",
    definition: "A monetary policy where a central bank purchases government securities to increase the money supply.",
    example: "Quantitative easing can help stimulate the economy during a recession.",
    relatedTerms: ["Inflation", "Economy", "Interest"],
  },
  {
    id: "gt-036",
    term: "Recession",
    partOfSpeech: "noun",
    definition: "A period of temporary economic decline during which trade and industrial activity are reduced.",
    example: "During a recession, it can be harder for students to find part-time jobs.",
    relatedTerms: ["Economy", "Inflation", "Gross Income"],
  },
  {
    id: "gt-037",
    term: "Underwriting",
    partOfSpeech: "verb",
    definition: "The process through which an individual or institution takes on financial risk for a fee.",
    example: "Insurance companies use underwriting to determine how much coverage to provide.",
    relatedTerms: ["Risk", "Insurance", "Bank"],
  },
  {
    id: "gt-038",
    term: "Volatility",
    partOfSpeech: "noun",
    definition: "The degree of variation of a trading price series over time.",
    example: "Crypto is known for its high volatility; prices can change drastically in minutes.",
    relatedTerms: ["Risk", "Market", "Investment"],
  },
  {
    id: "gt-039",
    term: "Working Capital",
    partOfSpeech: "noun",
    definition: "The capital of a business which is used in its day-to-day operations.",
    example: "Small businesses need enough working capital to pay their suppliers and employees.",
    relatedTerms: ["Cash Flow", "Asset", "Liability"],
  },
  {
    id: "gt-040",
    term: "X-efficiency",
    partOfSpeech: "noun",
    definition: "The degree of efficiency maintained by firms under conditions of imperfect competition.",
    example: "X-efficiency is often lower in monopolies where there is no pressure to compete.",
    relatedTerms: ["Economy", "Efficiency", "Market"],
  },
  {
    id: "gt-041",
    term: "Yield",
    partOfSpeech: "noun",
    definition: "The income return on an investment, such as the interest or dividends received.",
    example: "Calculating the yield helps you compare the profitability of different bonds.",
    relatedTerms: ["Interest", "Dividend", "Return"],
  },
  {
    id: "gt-042",
    term: "Zero-coupon Bond",
    partOfSpeech: "noun",
    definition: "A bond that is issued at a deep discount to its face value but pays no interest.",
    example: "A zero-coupon bond gains value as it approaches its maturity date.",
    relatedTerms: ["Bond", "Discount", "Interest"],
  },
];
